import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Search, Wand2 } from "lucide-react";
import { useState } from "react";

import { AppShell, PageHeader } from "@/components/AppShell";
import { Disclaimer, ResultPanel } from "@/components/AiResult";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { runResearch } from "@/lib/ai.functions";

export const Route = createFileRoute("/research")({
  head: () => ({
    meta: [
      { title: "AI Research Assistant | KAT AI Assistant" },
      {
        name: "description",
        content:
          "Get structured research briefings with insights, opportunities, risks and next steps.",
      },
      { property: "og:title", content: "AI Research Assistant | KAT AI Assistant" },
      {
        property: "og:description",
        content: "Balanced, decision-ready research briefings generated by AI.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: ResearchPage,
});

const DEPTHS = ["Quick brief", "Standard briefing", "Deep dive"];

function ResearchPage() {
  const run = useServerFn(runResearch);
  const [topic, setTopic] = useState("");
  const [depth, setDepth] = useState<string>("Standard briefing");
  const [angle, setAngle] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<string | null>(null);

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!topic.trim()) return;
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await run({ data: { topic, depth, angle } });
      setResult(res.text);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <AppShell>
      <PageHeader
        icon={Search}
        title="AI Research Assistant"
        description="Ask about a market, tool, competitor or concept and get a structured briefing you can act on."
      />
      <div className="mx-auto grid max-w-5xl gap-6 px-5 py-8 sm:px-8 lg:grid-cols-2">
        <form
          onSubmit={onSubmit}
          className="space-y-4 rounded-2xl border border-border bg-card p-5 shadow-card"
        >
          <div className="space-y-2">
            <Label htmlFor="topic">Research topic</Label>
            <Input
              id="topic"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="Adoption of AI note-takers in mid-market consulting firms"
            />
          </div>
          <div className="space-y-2">
            <Label>Depth</Label>
            <Select value={depth} onValueChange={setDepth}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {DEPTHS.map((d) => (
                  <SelectItem key={d} value={d}>
                    {d}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="angle">Decision context (optional)</Label>
            <Textarea
              id="angle"
              rows={5}
              value={angle}
              onChange={(e) => setAngle(e.target.value)}
              placeholder="We're deciding whether to build or buy before Q4 planning."
            />
          </div>
          <Button type="submit" disabled={loading || !topic.trim()} className="w-full">
            <Wand2 className="size-4" />
            {loading ? "Researching…" : "Run research"}
          </Button>
          <Disclaimer />
        </form>

        <ResultPanel
          loading={loading}
          error={error}
          result={result}
          emptyHint="You'll get an overview, key insights, opportunities and risks, and what to verify."
        />
      </div>
    </AppShell>
  );
}
